import type { CareCategory, GoalMetric } from "@/lib/generated/prisma/client";

/**
 * Curadoria própria em PT-BR (mesmo espírito de wellnessFacts.ts), não
 * gerada por IA. Cada lista tem 24 dicas — cobre metas de até 120 dias
 * (4 meses, o próprio exemplo de perda de peso) no intervalo de 5 dias
 * (TIP_INTERVAL_DAYS em lib/goals/goalCore.ts) sem repetir nenhuma. Metas
 * mais longas que isso voltam a ciclar pela lista (pickTipForIndex usa
 * módulo) — dá pra ampliar de novo se precisar cobrir prazos maiores.
 * Cada lista segue um arco (início → meio → fim da meta), misturando
 * reforço de comportamento, gatilho mental e estratégia prática.
 */

const PESO_TIPS: string[] = [
  "Beba um copo de água antes das refeições — ajuda a chegar à mesa com menos fome e evita comer além da conta.",
  "Comece o prato pelas proteínas e fibras (carnes magras, ovos, vegetais) antes dos carboidratos — isso reduz o pico de fome logo depois de comer.",
  "Dormir menos de 7 horas por noite mexe nos hormônios que controlam o apetite. Cuidar do sono é parte do processo de perder peso, não um extra.",
  "Movimento fora do treino conta: subir escada, caminhar até um lugar próximo, ficar em pé mais tempo. Pequenas escolhas ao longo do dia somam mais do que parecem.",
  "É normal a perda de peso desacelerar ou parar por alguns dias mesmo fazendo tudo certo — o corpo se ajusta em degraus, não numa linha reta. Não é sinal de que parou de funcionar.",
  "Não confie na força de vontade sozinha: deixe à vista só o que ajuda (fruta na mesa, água na geladeira) e guarde longe o que atrapalha. Ambiente bem organizado facilita mais que disciplina.",
  "Coma devagar e preste atenção em quando a fome passa — o cérebro leva uns 15-20 minutos pra registrar saciedade. Comer rápido demais é convite a repetir o prato sem precisar.",
  "Inclua algum exercício de força (mesmo peso do próprio corpo) — ajuda a preservar músculo enquanto o peso cai, o que mantém o metabolismo mais ativo.",
  "Fibras presentes em vegetais, frutas e grãos integrais aumentam a saciedade — ajudam a comer menos sem passar fome.",
  "Evite rotular comidas como \"proibidas\". Isso costuma aumentar a vontade delas — pensar em frequência e quantidade funciona melhor do que proibição total.",
  "A balança varia de um dia pro outro por retenção de líquido, não só gordura. Olhe a tendência de 1-2 semanas, não o número isolado de hoje.",
  "Na metade do caminho é normal a empolgação inicial diminuir um pouco — nessa fase, apoiar-se na rotina já construída pesa mais do que depender de motivação.",
  "Um dia fora da dieta não apaga semanas de progresso. O que importa é o padrão da maioria dos dias, não a perfeição — volte pra rotina no próximo prato, sem culpa.",
  "Em refeições fora de casa, escolha com calma o prato principal e vá com moderação nos extras — funciona melhor do que tentar \"compensar\" depois.",
  "Bebidas alcoólicas têm calorias que passam despercebidas — vale contar como parte da refeição, não como algo à parte.",
  "Preparar refeições com antecedência (meal prep) reduz decisões de última hora, que costumam pesar mais pro lado que você não queria.",
  "Acompanhar o progresso não precisa virar obsessão — pesar-se ou medir 1-2 vezes por semana já é suficiente pra ver a tendência real.",
  "Preste atenção em sinais além da balança: disposição, sono, roupas mais confortáveis. Também são progresso de verdade.",
  "Épocas de mais estresse ou mudança na rotina podem desacelerar o processo temporariamente — não significa que parou de funcionar.",
  "Se bater vontade de repetir um prato, espere alguns minutos antes de decidir — a sensação de fome muitas vezes passa nesse intervalo.",
  "Contar com alguém — comentar sua meta com um amigo ou familiar — aumenta bastante a chance de continuar nos dias difíceis.",
  "Pequenas vitórias ao longo do caminho (uma roupa que serviu diferente, mais disposição pra subir escada) merecem ser celebradas, não só o número final.",
  "Reta final: revisite o motivo que te trouxe até aqui — lembrar do \"porquê\" ajuda a manter o ritmo quando a novidade inicial já passou.",
  "Perto do fim da meta: o que sustenta o resultado depois é o hábito construído, não a meta em si. Pense em como isso já virou parte natural da sua rotina.",
];

const PRESSAO_TIPS: string[] = [
  "Reduza o sal escondido, não só o do saleiro: temperos prontos, embutidos e produtos industrializados costumam ter mais sódio do que parece.",
  "Alimentos ricos em potássio (banana, folhas verdes, feijão) ajudam o corpo a equilibrar o efeito do sódio na pressão.",
  "Meça sempre do mesmo jeito: no mesmo braço, sentado(a), depois de 5 minutos em repouso. Medições inconsistentes fazem o número parecer mais instável do que realmente é.",
  "Reduzir o consumo de álcool tem efeito direto na pressão arterial, mesmo em quantidades moderadas.",
  "Caminhada regular, mesmo em ritmo leve, ajuda a baixar a pressão ao longo das semanas — não precisa ser um treino intenso pra fazer diferença.",
  "Respiração lenta e profunda por alguns minutos ativa uma resposta do corpo que reduz a pressão na hora — útil especialmente antes de medir.",
  "Sono ruim ou insuficiente também influencia a pressão arterial. Cuidar do sono é parte do cuidado com a pressão, não algo separado.",
  "Cafeína pode elevar a pressão temporariamente — evite medir logo depois do café se quiser um número mais representativo do seu dia a dia.",
  "Reduza processados em geral, não só o sal — costumam vir com sódio e gordura juntos, os dois de olho na pressão.",
  "Praticar técnicas de relaxamento regularmente (não só quando está estressado) tem efeito acumulado na pressão ao longo das semanas.",
  "Fumar eleva a pressão a cada cigarro — reduzir ou parar tem impacto direto e mensurável no controle a longo prazo.",
  "Evite medir logo após esforço físico intenso — espere alguns minutos de descanso antes.",
  "Manter um registro das leituras (o app ajuda com isso) mostra o padrão real pro seu médico, não só números isolados de consultas espaçadas.",
  "Gordura na região abdominal está mais associada à pressão alta do que o peso total — atividade física ajuda especialmente aí.",
  "Bexiga cheia na hora de medir pode alterar o resultado — vá ao banheiro antes de medir, se possível.",
  "Manga apertada no braço durante a medição também pode interferir — prefira manga curta ou arregaçada na hora de aferir.",
  "Se peso e pressão andam juntos no seu caso, perder uma quantidade pequena de peso já costuma ajudar a pressão a melhorar também.",
  "Controlar o estresse do dia a dia, mesmo sem eliminar a causa, já ajuda a reduzir picos de pressão ao longo da semana.",
  "Manter os horários dos remédios em dia (a Rotina do app ajuda) é uma das coisas que mais impacta o controle da pressão a longo prazo.",
  "Atividade física consistente, mesmo leve, tem mais efeito a longo prazo do que esforços intensos e esporádicos.",
  "Uma leitura alta isolada não define o quadro — olhe o padrão de várias medições ao longo do tempo, não um número único fora da curva.",
  "Se notar leituras consistentemente altas por vários dias seguidos, converse com seu médico — não espere a próxima consulta de rotina se for um padrão novo.",
  "Qualquer melhora na direção certa vale a pena registrar e comemorar, mesmo sem uma meta numérica fechada.",
  "Perto do fim da meta: o hábito de medir e cuidar regularmente é o que realmente protege a longo prazo — vale manter mesmo depois do prazo.",
];

const ROTINA_TIPS_BY_CATEGORY: Record<CareCategory, string[]> = {
  ESTUDOS: [
    "Técnica pomodoro: 25 minutos de foco total + 5 de pausa. Blocos curtos mantêm a concentração melhor do que tentar estudar horas seguidas.",
    "Revisão espaçada rende mais que reler tudo de uma vez: revise o mesmo conteúdo em intervalos crescentes — 1 dia depois, 3 dias depois, 1 semana depois.",
    "Antes de checar a resposta, tente responder de memória. Forçar o cérebro a buscar a informação (não só reconhecê-la) é o que realmente fixa o conteúdo.",
    "Celular fora de vista durante o estudo — cada notificação quebra o foco por vários minutos até voltar ao nível de concentração anterior.",
    "Explicar o conteúdo em voz alta, como se estivesse ensinando alguém, revela rápido o que você realmente entendeu e o que ainda está superficial.",
    "Misturar temas diferentes numa mesma sessão de estudo (em vez de esgotar um assunto só) ajuda mais a memória a longo prazo, mesmo parecendo mais difícil na hora.",
    "Dia de pouca concentração? 20 minutos focados valem mais que 2 horas distraído(a). Reduza o tempo, não pule o dia.",
    "Anotar à mão processa a informação de um jeito mais profundo do que digitar, pra boa parte das pessoas — vale testar nos resumos.",
    "Comece pela parte mais difícil quando a energia estiver mais alta — geralmente no início da sessão de estudo.",
    "Grifar com moderação: grifar demais dá sensação de estar estudando sem realmente processar o conteúdo.",
    "Fazer resumos com suas próprias palavras (não copiar o texto original) exige entender de verdade, não só reconhecer.",
    "Alternar entre ler e praticar exercícios mantém o cérebro mais ativo do que só ler por horas seguidas.",
    "Decida o que vai estudar antes de sentar à mesa — assim você não perde os primeiros minutos (os de maior disposição) só decidindo por onde começar.",
    "Definir um horário de término, não só de início, cria uma pressão saudável que ajuda a manter o foco durante a sessão.",
    "Errar questões faz parte do aprendizado — reveja o motivo do erro em vez de só marcar como errado e seguir em frente.",
    "Descanse a cada 45-60 minutos com uma pausa curta — o cérebro absorve menos depois de muito tempo sem intervalo.",
    "Resolver exercícios e simulados treina mais do que reler a teoria — praticar o formato da prova é parte do aprendizado, não só revisão.",
    "Se distrair é normal — perceber a distração e voltar ao foco, sem se cobrar demais por isso, já é parte do treino de concentração.",
    "Dormir bem na noite depois de estudar ajuda o cérebro a consolidar o conteúdo. Virar a madrugada estudando geralmente rende menos do que parece na hora.",
    "Revisar o material antes de dormir, mesmo rapidinho, ajuda a consolidar o que foi visto durante o dia.",
    "Simular a prova em condições parecidas (tempo cronometrado, sem consulta) treina não só o conteúdo, mas o controle da ansiedade na hora H.",
    "Comemorar metas de estudo cumpridas — não só notas — reforça o hábito de continuar, independente do resultado final.",
    "Reta final: revise o que você estudou semanas atrás, não só o conteúdo mais recente — voltar ao início é o que realmente fixa tudo.",
    "Perto do fim da meta: faça uma revisão geral ligando os pontos — é isso que transforma memorização em entendimento de verdade.",
  ],
  TREINO: [
    "Separe a roupa de treino na noite anterior — reduz o atrito de começar, principalmente nos dias mais corridos.",
    "Nos dias sem vontade, comprometa-se só com o aquecimento. Na maioria das vezes, o treino inteiro acontece depois que você já começou.",
    "Dor muscular leve nos primeiros dias é normal; dor articular ou aguda não é. Ouça o corpo e ajuste a carga quando precisar.",
    "Descanso é parte do treino, não o oposto dele — o músculo se fortalece no dia de recuperação, não só durante o esforço.",
    "Aumente carga, repetições ou tempo aos poucos. Evoluir rápido demais é uma das causas mais comuns de lesão e de desistência.",
    "Treinar sempre no mesmo horário ajuda o corpo (e a cabeça) a esperar por aquilo automaticamente, sem precisar decidir toda vez.",
    "Treinou menos tempo do que planejado? Marque como feito mesmo assim — consistência pesa mais que uma sessão perfeita.",
    "Treinar com alguém ou compartilhar o progresso aumenta bastante a chance de continuar depois do primeiro mês, quando a empolgação inicial passa.",
    "Aquecer antes e alongar depois reduz o risco de lesão e ajuda na recuperação pro próximo treino.",
    "Defina metas de processo (treinar X vezes na semana) além de metas de resultado — elas estão sob seu controle todo dia.",
    "Se sentir dor aguda durante o exercício, pare. \"Treinar com dor\" não é sinônimo de disciplina, é risco de lesão maior.",
    "Alimentar-se bem nas horas ao redor do treino (antes e depois) influencia diretamente o desempenho e a recuperação.",
    "Hidratação antes e depois do treino influencia direto no desempenho e na recuperação — não é só durante o exercício que importa.",
    "Registrar cargas, tempos ou repetições ajuda a enxergar progresso que não aparece no espelho de um dia pro outro.",
    "Semanas mais cansativas pedem treinos mais leves, não necessariamente treino zero — ajustar a intensidade mantém o hábito vivo.",
    "Sentir resistência pra começar é comum mesmo em quem já treina há anos — a diferença é começar mesmo assim, não a ausência de resistência.",
    "Variar o tipo de exercício de vez em quando reduz o tédio e evita que o corpo se acostume demais com o mesmo estímulo.",
    "Cuidar da mobilidade evita que pequenas dores acumuladas virem um motivo real pra parar mais na frente.",
    "Comparar-se com a própria evolução, não com o ritmo de outras pessoas, sustenta a motivação por mais tempo.",
    "Treinos curtos e consistentes valem mais no total do que treinos longos e esporádicos que você não sustenta.",
    "Se perder a sequência por algum motivo (viagem, doença), retome de onde parou, sem tentar recuperar tudo de uma vez.",
    "Comemore os dias seguidos treinando, não só o resultado final (peso, medidas). O processo é o que você controla todo dia.",
    "Reta final: pense em qual frequência de treino é realmente sustentável a longo prazo — o corpo agradece consistência, não excesso pontual.",
    "Perto do fim da meta: pense em manter o treino como parte da rotina, não como algo que termina quando o prazo acaba.",
  ],
  ALIMENTACAO: [
    "Planejar as refeições da semana com antecedência evita decisões de última hora — que tendem pro caminho mais fácil, não o mais saudável.",
    "Ter opções saudáveis já prontas ou cortadas na geladeira facilita a escolha certa na hora em que bate a fome.",
    "Evite ir ao mercado com fome — aumenta bastante a chance de colocar no carrinho coisas que não estavam no plano.",
    "Trocar aos poucos (por exemplo, refrigerante por água com limão) costuma durar mais do que mudar tudo de uma vez.",
    "Comer em horários mais regulares ajuda a evitar picos de fome que levam a exagerar na refeição seguinte.",
    "Um dia fora do planejado não estraga a semana — volte ao padrão na próxima refeição, sem tentar compensar exagerando pro outro lado.",
    "Ler o rótulo dos alimentos ajuda a notar açúcar e sódio escondidos em produtos que parecem inofensivos à primeira vista.",
    "Levar um lanche saudável quando sair de casa reduz a tentação de comprar algo não planejado no meio do dia.",
    "Montar o prato com metade de vegetais, um quarto de proteína e um quarto de carboidrato é um jeito simples de equilibrar sem calcular nada.",
    "Beber água ao longo do dia às vezes reduz a sensação de fome que na verdade era sede.",
    "Ter uma lista de compras antes de ir ao mercado reduz bastante as compras por impulso.",
    "Preparar tempero e vegetais com antecedência (mise en place) reduz o esforço de cozinhar nos dias corridos.",
    "Cozinhar em maior quantidade e congelar porções facilita muito nos dias mais corridos da semana.",
    "Comer devagar e sem tela por perto ajuda o corpo a perceber o momento certo de parar.",
    "Evite pular refeições pra \"economizar\" calorias — geralmente leva a comer mais na refeição seguinte.",
    "Testar uma receita nova por semana mantém a alimentação saudável interessante, em vez de repetitiva.",
    "Frutas e vegetais da estação costumam ser mais baratos e mais saborosos — vale ajustar o cardápio ao que está na safra.",
    "Guarnições prontas (arroz integral, feijão, legumes) em potes individuais facilitam montar uma refeição equilibrada rápido.",
    "Prestar atenção em como cada alimento faz você se sentir depois (disposição, digestão) ajuda a escolher por experiência própria, não só por regra.",
    "Se comer fora de casa é frequente, escolher bem o restaurante importa tanto quanto o que você pede lá.",
    "Envolver quem mora com você na mudança torna mais fácil manter — comer diferente do resto da casa sozinho(a) é mais difícil.",
    "Pequenos ajustes mantidos por meses valem mais que mudanças radicais que duram poucas semanas.",
    "Reta final: observe quais mudanças já viraram automáticas — essas são as que vieram pra ficar.",
    "Perto do fim da meta: trate isso como o novo padrão do dia a dia, não como uma fase temporária que termina no prazo.",
  ],
  MEDICACAO: [
    "Vincule o remédio a algo que você já faz todo dia — escovar os dentes, tomar café — pra reduzir esquecimentos.",
    "Deixe a caixinha do remédio à vista, não guardada no fundo do armário. O que está visível funciona como lembrete natural.",
    "Organizadores de comprimidos por dia da semana ajudam a notar rápido se alguma dose ficou pra trás.",
    "Um alarme no horário certo tira a dependência de \"lembrar sozinho\" — principalmente em dias corridos.",
    "Se esquecer uma dose, siga a orientação do médico ou farmacêutico sobre o que fazer — não dobre a próxima dose por conta própria.",
    "Levar o remédio quando for viajar ou sair de casa por mais tempo evita interrupções no tratamento.",
    "Entender o motivo do tratamento (não só segui-lo por seguir) costuma aumentar bastante a adesão a longo prazo.",
    "Anotar quando a cartela ou o frasco está acabando ajuda a se planejar pra recomprar a tempo, sem ficar sem.",
    "Guardar o remédio em local com temperatura estável (fora do banheiro, geralmente úmido) preserva melhor a qualidade.",
    "Conferir a validade periodicamente evita descobrir que o remédio venceu justamente na hora de tomar.",
    "Em caso de troca de marca ou genérico, converse com o farmacêutico sobre eventuais diferenças — geralmente é só embalagem, mas vale confirmar.",
    "Anotar dúvidas sobre o tratamento pra perguntar na próxima consulta evita ficar com incerteza por meses.",
    "Se o horário combinado não encaixa mais na rotina (mudou de turno, por exemplo), é válido perguntar ao médico sobre ajustar.",
    "Ter um \"plano B\" pra dias fora de casa — levar uma dose extra na bolsa — evita ficar sem quando os planos mudam de última hora.",
    "Compartilhar a lista de medicamentos em uso com todos os médicos que você consulta evita interações não percebidas.",
    "Sentiu algum efeito colateral? Converse com o médico em vez de simplesmente parar de tomar por conta própria.",
    "Pequenas melhoras no sintoma não significam que pode parar por conta própria — o tratamento tem um tempo definido pelo médico.",
    "Se tiver dificuldade de engolir ou algum incômodo com a forma do remédio, comente com o médico — às vezes existe alternativa.",
    "Revisar com o médico se ainda faz sentido manter todos os remédios em uso evita acumular medicação desnecessária ao longo do tempo.",
    "Guardar fora do alcance de crianças e animais é parte do cuidado, não só tomar certo.",
    "Manter o mesmo horário todo dia reduz picos e quedas do medicamento no organismo — regularidade importa tanto quanto não esquecer.",
    "Se toma mais de um remédio, organizar por horário do dia (manhã, tarde, noite) simplifica bastante a lembrança.",
    "Levar a lista de remédios (ou o app) em consultas evita esquecer de mencionar algo que está em uso.",
    "Perto do fim da meta: o hábito de tomar certo é o que sustenta o tratamento — vale manter mesmo depois do prazo da meta acabar.",
  ],
  TERAPIA: [
    "Marcar as sessões no calendário como um compromisso fixo ajuda a não deixá-las de lado nas semanas mais corridas.",
    "Anotar entre as sessões o que quer conversar evita esquecer pontos importantes na hora da consulta.",
    "Nem toda sessão precisa parecer \"produtiva\" pra estar fazendo efeito — o processo terapêutico é cumulativo, não linear.",
    "Praticar entre as sessões o que foi conversado (quando orientado) costuma ser o que traz mudança real no dia a dia.",
    "É normal sentir resistência ou vontade de faltar em fases mais difíceis — muitas vezes é justamente aí que mais ajuda.",
    "Ser honesto(a) com o profissional, mesmo sobre o que é desconfortável de falar, é o que faz o processo avançar de verdade.",
    "Mudanças emocionais consistentes costumam levar semanas ou meses pra aparecer, não dias — dar tempo ao processo faz parte.",
    "Reservar um tempo antes ou depois da sessão pra desacelerar ajuda a aproveitar melhor o momento.",
    "Chegar um pouco antes da sessão, sem pressa, ajuda a entrar num estado mais presente pra aproveitar o tempo.",
    "Trocar de terapeuta quando não sente conexão não é fracasso — encontrar o profissional certo faz parte do processo.",
    "Terapia não substitui apoio médico quando necessário (psiquiatra, por exemplo) — os dois podem coexistir e se complementar.",
    "Momentos difíceis fora da sessão também são material valioso pra trazer — não precisa esperar \"organizar os pensamentos\" antes.",
    "Reconhecer um padrão se repetindo, mesmo que incômodo, já é parte do trabalho — perceber vem antes de mudar.",
    "Nem tudo precisa ser resolvido na terapia — alguns temas levam tempo e ciclos diferentes pra amadurecer.",
    "Cuidar de relações fora da terapia (amizades, família) é parte do que sustenta a saúde emocional no dia a dia.",
    "Evite comparar seu processo com o de outras pessoas — cada história pede um tempo e um caminho diferente.",
    "Praticar auto-observação sem julgamento entre as sessões ajuda a chegar com mais clareza no que quer conversar.",
    "Pequenos avanços — dormir melhor, reagir diferente numa situação — merecem ser reconhecidos como parte do progresso.",
    "Se algo na terapia não estiver fazendo sentido pra você, comentar com o profissional é válido — o processo é colaborativo.",
    "Manter a terapia mesmo em fases boas ajuda a consolidar ganhos, não só a lidar com crises.",
    "Sono, alimentação e movimento também sustentam a saúde mental — não são coisas separadas do cuidado emocional.",
    "Perceber avanços em como você reage a situações antigas é um sinal concreto de progresso, mesmo sem \"sentir diferente\" o tempo todo.",
    "Reta final: pense no que você quer levar dessa fase adiante, mesmo depois que o prazo da meta terminar.",
    "Perto do fim da meta: registre o que mudou desde o início — às vezes o avanço só fica claro quando se olha pra trás.",
  ],
  OUTRO: [
    "Encaixe o novo hábito logo depois de algo que você já faz todo dia — é mais fácil lembrar de algo colado a uma rotina existente.",
    "Deixe um lembrete visual no caminho: o que está à vista tem muito mais chance de acontecer do que o que fica guardado.",
    "Nos dias difíceis, prometa a si mesmo só 2 minutos. Começar costuma ser a parte mais difícil — uma vez começando, seguir fica mais fácil.",
    "Decida com antecedência quando e onde vai fazer, não só que vai fazer. Um plano específico funciona muito mais que uma intenção vaga.",
    "Se pular um dia, o objetivo é não pular dois seguidos — uma falha não desfaz o progresso, mas deixar a sequência de faltas crescer é o que atrapalha de verdade.",
    "Marcar a conclusão do dia dá uma recompensa imediata pro cérebro — é normal sentir que vale a pena só de ver o item riscado.",
    "Deixe tudo pronto com antecedência — reduzir o esforço pra começar é mais eficaz do que tentar aumentar a motivação.",
    "Junte o hábito a algo que você gosta — isso cria uma associação positiva com o momento, em vez de sentir como obrigação.",
    "Comece pequeno de propósito — é mais fácil manter um hábito modesto todo dia do que um ambicioso só às vezes.",
    "Prepare o ambiente com antecedência pra reduzir decisões no momento de fazer — menos escolhas, mais ação.",
    "Revisar a meta semanalmente (não só no dia a dia) ajuda a perceber ajustes necessários antes que vire desistência.",
    "Se um gatilho específico sempre atrapalha (horário, lugar, companhia), identifique e mude esse gatilho, não só tente ter mais disciplina.",
    "Hábitos vinculados a horários fixos do relógio biológico (manhã, por exemplo) tendem a ser mais fáceis de manter que horários variáveis.",
    "Dias de exceção acontecem — o que importa é ter um plano claro de retomada, não evitar exceções pra sempre.",
    "Se o tamanho original parecer pesado demais num dia corrido, reduza em vez de pular o dia inteiro. Ajustar é melhor que abandonar.",
    "Celebrar a sequência motiva, mas não deixe uma quebra nela apagar todo o progresso construído até ali.",
    "Buscar apoio de quem já passou por hábito parecido pode trazer atalhos que você não teria descoberto sozinho(a).",
    "Contar pra alguém que você está com essa meta cria um compromisso além de você mesmo(a) — ajuda a persistir nos dias difíceis.",
    "Ajustar o hábito conforme a fase da vida (trabalho mais puxado, por exemplo) é mais sustentável do que insistir num formato rígido.",
    "Registrar o motivo original da meta em algum lugar visível ajuda a lembrar dele nos dias de pouca vontade.",
    "Pequenas recompensas ao longo do caminho, não só no final, ajudam o cérebro a associar o hábito com algo positivo.",
    "Lembrar do motivo por trás da meta pesa mais nos dias de pouca vontade do que tentar forçar a disciplina sozinho(a).",
    "Repita o suficiente e a atividade deixa de ser esforço e vira identidade — é aí que o hábito se sustenta sozinho.",
    "Perto do fim da meta: o que vai sustentar isso depois é o hábito em si, não o prazo — pense em como ele já faz parte do seu dia.",
  ],
};

export function pickTipForIndex(
  metric: GoalMetric,
  index: number,
  category?: CareCategory | null
): string {
  if (metric === "PESO") return PESO_TIPS[index % PESO_TIPS.length];
  if (metric === "PRESSAO") return PRESSAO_TIPS[index % PRESSAO_TIPS.length];
  const tips = ROTINA_TIPS_BY_CATEGORY[category ?? "OUTRO"];
  return tips[index % tips.length];
}
